### ISSUE TITLE
Thank you for that great Project!

### ISSUE THREAD

**Issue by KarlZeilhofer** [kbricks/kbricks-core#8]
Hi, 

our Prusa i3 MK3S is currently down for maintenance, but I think the tractor will be one of the first models it will print, when it is ready again for production. :)

Greets from Austria, 
Karl

**Comment by robkern** [comment]
Hi Karl,
Thanks for your feedback which I have just seen today! Hope you will share a picture of your work on Thiniverse and hope you will checkout the new tipper truck as well ;-)

Regards,
Robert
